* version 0.1
  initial cut, no authentication, poorly written python code, just trying to learn.
  Can browse to all videos and play the clips -- need authenticaiton to get full videos
** Bugs
   There are some bugs regarding the sites get class description url 
   -- "/_ajax_get_class_description.php?"
   it doesn't return a title for some videos so I'm getting in index out of range error
*** Menu items affected by this
**** DONE Level 1
     CLOSED: [2013-11-03 Sun 12:13]
**** DONE Level 3
     CLOSED: [2013-11-03 Sun 12:13]
**** DONE 5 min
     CLOSED: [2013-11-03 Sun 12:13]
**** DONE 10 min
     CLOSED: [2013-11-03 Sun 12:13]
**** DONE 75 min
     CLOSED: [2013-11-03 Sun 12:13]
**** DONE 120 min
     CLOSED: [2013-11-03 Sun 12:13]

** Fixes
   Just try except and if an error comes up give it a default name of its style of yoga
* version 0.1.1
  fixes to 0.1's bugs
* version 0.2
** Logging in with xbmc settings from configure
** Initial Code Refactory
** If no cookie file is present attempts to log on to YogaGlo when the class is initialized.
** If there is a cookie present assumes that you are logged on, I haven't had any problems with cookie expiring yet.
*** BUGS
    Cookie file is present but is expired -- code shows as logged on, but definitely need to re-log on
* version 0.2.1
  Fix of expired cookie session -- not the way I would want it, but I think session expiration is handled on yg's server so impossible to tell from cookie when expires
  solution was to try and use cookie to get on to myaccounttoday.php and search for 'Welcome back' if this doesn't work then we need to login again.
* version 0.3
  Adding video information to info menu - teacher, level, duration, style
